# Generated by Django 4.1.4 on 2023-03-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("pid", models.CharField(default="", max_length=255)),
                ("view_count", models.IntegerField()),
                ("se", models.IntegerField(default=0)),
                ("vc", models.IntegerField(default=0)),
                ("time", models.IntegerField(default=0)),
            ],
        ),
    ]
